### ISSUE TITLE
Collapse Sound modes to the key switches and not encoder modes

### ISSUE THREAD

**Issue by lithochasm** [dczia/Defcon27-Badge#10]
Lets move hold / fixed / doom mode to key switches and not encoder clicks if possible

**Comment by mediumrehr** [comment]
hmm the plan was to use the the keys to change waveform and the encoder to change octave. i guess we could use first three keys (DCZ) to change audio mode (fixed, hold, doom) and the last two (IA) to adjust octave. then the encoder could change waveform, or we could flip that and encoder would do octave and IA buttons cycle waveform, or we just get rid of octave changing.

**Comment by lithochasm** [comment]
Now that I hear your plan I think it’s cleaner to go with that. Do we need
hold mode? I just wanted to reduce the number of clicks people had to make
in case they need to transition to a quiet mode quickly.

**Comment by mediumrehr** [comment]
fixed volume makes sense to me. the others don't seem like they need to be modes to me. i think it'd be cool to make doom more of an easter egg. maybe holding all the keys down? something you'd have to try to get into, it's unlikely it'd just get pressed by accident.

**Comment by lithochasm** [comment]
That’s a good idea, I like it

**Comment by Ancient123** [comment]
I like the Doom mode as an easter egg thing. 👍 
I am down with removing hold mode, I was just playing around with stuff.

**Comment by lithochasm** [comment]
Good job folks. Closing this issue.
